import { NavBar } from "../NavBar";
import { useRouter } from "next/router";
import Head from "next/head";

export const Header = () => {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Nickland.me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar
        label="navbar"
        className="text-white bg-gray-800 text-center flex justify-between items-center p-4"
      >
        <button className="text-3xl" onClick={() => router.push("/")}>
          Nick Land
        </button>
        <div className="inline-flex space-x-4 text-lg">
          <button
            className={`${router.pathname === "/about" && "text-gray-400"}`}
            onClick={() => router.push("/about")}
          >
            About
          </button>
          <button
            className={`${router.pathname === "/contact" && "text-gray-400"}`}
            onClick={() => router.push("/contact")}
          >
            Contact
          </button>
        </div>
      </NavBar>
    </>
  );
};
