import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { NavBar } from "../components/NavBar";
import { ExclamationIcon } from "@heroicons/react/solid";

const Home: NextPage = () => {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Nickland.me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar
        label="navbar"
        className="text-white bg-gray-800 text-center flex justify-between items-center p-4"
      >
        <div className="text-3xl">Nickland.me</div>
        <div className="flex space-x-4">
          <button onClick={() => router.push("/about")}>About</button>
          <button onClick={() => router.push("/contact")}>Contact</button>
        </div>
      </NavBar>
      <div className="flex flex-col text-lg p-4 text-center">
        <ul>
          <li>Dad</li>
          <li>Learner</li>
          <li>Tinkerer</li>
        </ul>
        <p className="pt-4">
          I am a master of none; I am a jack of all trades. I have many hobbies,
          and coding is one of them.
          <span className="flex justify-center items-center text-red-500">
            <ExclamationIcon className="w-8 " />
            <span className="mx-2">
              This site is under construction, I will be updating often, so
              please check back!
            </span>
            <ExclamationIcon className="w-8 " />
          </span>
        </p>
      </div>
    </>
  );
};

export default Home;
