import type { NextPage } from "next";
import Head from "next/head";
import { NavBar } from "../components/NavBar";
import { ExclamationIcon } from "@heroicons/react/solid";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Nickland.me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar label="navbar" className="bg-gray-800 p-2 text-center">
        <div className="text-white text-4xl">Nickland.me</div>
      </NavBar>
      <div className="flex flex-col text-lg p-4 text-center">
        <ul>
          <li>Dad</li>
          <li>Learner</li>
          <li>Tinkerer</li>
        </ul>
        <p className="pt-4">
          I am a master of none; I am a jack of all trades. I have many hobbies,
          and coding is one of them.
          <div className="flex justify-center text-red-500">
            <ExclamationIcon className="w-8 " />
            <span className="mx-2">
              This site is under construction, I will be updating often, so
              please check back!
            </span>
            <ExclamationIcon className="w-8 " />
          </div>
        </p>
      </div>
    </>
  );
};

export default Home;
